language: php

php:
    - 7.0
    - 7.1

sudo: false

cache:
    directories:
        - $HOME/.composer/cache/files

install:
    - composer install --no-interaction

script:
    - vendor/bin/phpunit --coverage-clover build/logs/clover.xml
    - vendor/bin/behat -f progress

after_success:
    - vendor/bin/coveralls
