os: linux

language: php

php:
    - 7.0
    - 7.1

node_js:
    - 7

sudo: false

cache:
    yarn: true
    directories:
        - $HOME/.composer/cache/files
        - node_modules
        - vendor

before_install:
    - yarn install

install:
    - composer install --no-interaction
    - bin/console maba:webpack:compile --env test

script:
    - vendor/bin/phpunit --coverage-clover build/logs/clover.xml
    - vendor/bin/behat -f progress

after_success:
    - vendor/bin/coveralls
